### ISSUE TITLE
rewriting some scss to cut down on amount of selectors

### ISSUE THREAD

**Issue by lukepearce** [ten4design/ten4-framework#59]
As I needed to add some extra row classes it's lead to quite a lot of selectors. I know that gzip handles compressing repetition well but it just seems messy.
```css
.row {
  margin-left: -64px; }
  .row.row--reverse {
    direction: rtl;
    text-align: left; }
  .row.row--centred {
    text-align: center; }
  .row.row--flush {
    margin-left: 0; }
  .row.row--small {
    margin-left: -32px; }
    .row.row--small .desk-1-12, .row.row--small .desk-2-12, .row.row--small .desk-3-12, .row.row--small .desk-4-12, .row.row--small .desk-5-12, .row.row--small .desk-6-12, .row.row--small .desk-7-12, .row.row--small .desk-8-12, .row.row--small .desk-9-12, .row.row--small .desk-10-12, .row.row--small .desk-11-12, .row.row--small .desk-12-12, .row.row--small .desk-1-5, .row.row--small .desk-2-5, .row.row--small .desk-3-5, .row.row--small .desk-4-5, .row.row--small .desk-5-5, .row.row--small .lap-1-12, .row.row--small .lap-2-12, .row.row--small .lap-3-12, .row.row--small .lap-4-12, .row.row--small .lap-5-12, .row.row--small .lap-6-12, .row.row--small .lap-7-12, .row.row--small .lap-8-12, .row.row--small .lap-9-12, .row.row--small .lap-10-12, .row.row--small .lap-11-12, .row.row--small .lap-12-12, .row.row--small .lap-1-5, .row.row--small .lap-2-5, .row.row--small .lap-3-5, .row.row--small .lap-4-5, .row.row--small .lap-5-5, .row.row--small .palm-1-12, .row.row--small .palm-2-12, .row.row--small .palm-3-12, .row.row--small .palm-4-12, .row.row--small .palm-5-12, .row.row--small .palm-6-12, .row.row--small .palm-7-12, .row.row--small .palm-8-12, .row.row--small .palm-9-12, .row.row--small .palm-10-12, .row.row--small .palm-11-12, .row.row--small .palm-12-12, .row.row--small .palm-1-5, .row.row--small .palm-2-5, .row.row--small .palm-3-5, .row.row--small .palm-4-5, .row.row--small .palm-5-5, .row.row--small .header__left-side, .row.row--small .nav__container {
      padding-left: 32px; }
  .row.row--tiny {
    margin-left: -16px; }
    .row.row--tiny .desk-1-12, .row.row--tiny .desk-2-12, .row.row--tiny .desk-3-12, .row.row--tiny .desk-4-12, .row.row--tiny .desk-5-12, .row.row--tiny .desk-6-12, .row.row--tiny .desk-7-12, .row.row--tiny .desk-8-12, .row.row--tiny .desk-9-12, .row.row--tiny .desk-10-12, .row.row--tiny .desk-11-12, .row.row--tiny .desk-12-12, .row.row--tiny .desk-1-5, .row.row--tiny .desk-2-5, .row.row--tiny .desk-3-5, .row.row--tiny .desk-4-5, .row.row--tiny .desk-5-5, .row.row--tiny .lap-1-12, .row.row--tiny .lap-2-12, .row.row--tiny .lap-3-12, .row.row--tiny .lap-4-12, .row.row--tiny .lap-5-12, .row.row--tiny .lap-6-12, .row.row--tiny .lap-7-12, .row.row--tiny .lap-8-12, .row.row--tiny .lap-9-12, .row.row--tiny .lap-10-12, .row.row--tiny .lap-11-12, .row.row--tiny .lap-12-12, .row.row--tiny .lap-1-5, .row.row--tiny .lap-2-5, .row.row--tiny .lap-3-5, .row.row--tiny .lap-4-5, .row.row--tiny .lap-5-5, .row.row--tiny .palm-1-12, .row.row--tiny .palm-2-12, .row.row--tiny .palm-3-12, .row.row--tiny .palm-4-12, .row.row--tiny .palm-5-12, .row.row--tiny .palm-6-12, .row.row--tiny .palm-7-12, .row.row--tiny .palm-8-12, .row.row--tiny .palm-9-12, .row.row--tiny .palm-10-12, .row.row--tiny .palm-11-12, .row.row--tiny .palm-12-12, .row.row--tiny .palm-1-5, .row.row--tiny .palm-2-5, .row.row--tiny .palm-3-5, .row.row--tiny .palm-4-5, .row.row--tiny .palm-5-5, .row.row--tiny .header__left-side, .row.row--tiny .nav__container {
      padding-left: 16px; }
  @media only screen and (max-width: 34.375em) {
    .row.row--tiny--on-mobile {
      margin-left: -16px; }
      .row.row--tiny--on-mobile .desk-1-12, .row.row--tiny--on-mobile .desk-2-12, .row.row--tiny--on-mobile .desk-3-12, .row.row--tiny--on-mobile .desk-4-12, .row.row--tiny--on-mobile .desk-5-12, .row.row--tiny--on-mobile .desk-6-12, .row.row--tiny--on-mobile .desk-7-12, .row.row--tiny--on-mobile .desk-8-12, .row.row--tiny--on-mobile .desk-9-12, .row.row--tiny--on-mobile .desk-10-12, .row.row--tiny--on-mobile .desk-11-12, .row.row--tiny--on-mobile .desk-12-12, .row.row--tiny--on-mobile .desk-1-5, .row.row--tiny--on-mobile .desk-2-5, .row.row--tiny--on-mobile .desk-3-5, .row.row--tiny--on-mobile .desk-4-5, .row.row--tiny--on-mobile .desk-5-5, .row.row--tiny--on-mobile .lap-1-12, .row.row--tiny--on-mobile .lap-2-12, .row.row--tiny--on-mobile .lap-3-12, .row.row--tiny--on-mobile .lap-4-12, .row.row--tiny--on-mobile .lap-5-12, .row.row--tiny--on-mobile .lap-6-12, .row.row--tiny--on-mobile .lap-7-12, .row.row--tiny--on-mobile .lap-8-12, .row.row--tiny--on-mobile .lap-9-12, .row.row--tiny--on-mobile .lap-10-12, .row.row--tiny--on-mobile .lap-11-12, .row.row--tiny--on-mobile .lap-12-12, .row.row--tiny--on-mobile .lap-1-5, .row.row--tiny--on-mobile .lap-2-5, .row.row--tiny--on-mobile .lap-3-5, .row.row--tiny--on-mobile .lap-4-5, .row.row--tiny--on-mobile .lap-5-5, .row.row--tiny--on-mobile .palm-1-12, .row.row--tiny--on-mobile .palm-2-12, .row.row--tiny--on-mobile .palm-3-12, .row.row--tiny--on-mobile .palm-4-12, .row.row--tiny--on-mobile .palm-5-12, .row.row--tiny--on-mobile .palm-6-12, .row.row--tiny--on-mobile .palm-7-12, .row.row--tiny--on-mobile .palm-8-12, .row.row--tiny--on-mobile .palm-9-12, .row.row--tiny--on-mobile .palm-10-12, .row.row--tiny--on-mobile .palm-11-12, .row.row--tiny--on-mobile .palm-12-12, .row.row--tiny--on-mobile .palm-1-5, .row.row--tiny--on-mobile .palm-2-5, .row.row--tiny--on-mobile .palm-3-5, .row.row--tiny--on-mobile .palm-4-5, .row.row--tiny--on-mobile .palm-5-5, .row.row--tiny--on-mobile .header__left-side, .row.row--tiny--on-mobile .nav__container {
        padding-left: 16px; } }
  .row.row--middle-align .desk-1-12, .row.row--middle-align .desk-2-12, .row.row--middle-align .desk-3-12, .row.row--middle-align .desk-4-12, .row.row--middle-align .desk-5-12, .row.row--middle-align .desk-6-12, .row.row--middle-align .desk-7-12, .row.row--middle-align .desk-8-12, .row.row--middle-align .desk-9-12, .row.row--middle-align .desk-10-12, .row.row--middle-align .desk-11-12, .row.row--middle-align .desk-12-12, .row.row--middle-align .desk-1-5, .row.row--middle-align .desk-2-5, .row.row--middle-align .desk-3-5, .row.row--middle-align .desk-4-5, .row.row--middle-align .desk-5-5, .row.row--middle-align .lap-1-12, .row.row--middle-align .lap-2-12, .row.row--middle-align .lap-3-12, .row.row--middle-align .lap-4-12, .row.row--middle-align .lap-5-12, .row.row--middle-align .lap-6-12, .row.row--middle-align .lap-7-12, .row.row--middle-align .lap-8-12, .row.row--middle-align .lap-9-12, .row.row--middle-align .lap-10-12, .row.row--middle-align .lap-11-12, .row.row--middle-align .lap-12-12, .row.row--middle-align .lap-1-5, .row.row--middle-align .lap-2-5, .row.row--middle-align .lap-3-5, .row.row--middle-align .lap-4-5, .row.row--middle-align .lap-5-5, .row.row--middle-align .palm-1-12, .row.row--middle-align .palm-2-12, .row.row--middle-align .palm-3-12, .row.row--middle-align .palm-4-12, .row.row--middle-align .palm-5-12, .row.row--middle-align .palm-6-12, .row.row--middle-align .palm-7-12, .row.row--middle-align .palm-8-12, .row.row--middle-align .palm-9-12, .row.row--middle-align .palm-10-12, .row.row--middle-align .palm-11-12, .row.row--middle-align .palm-12-12, .row.row--middle-align .palm-1-5, .row.row--middle-align .palm-2-5, .row.row--middle-align .palm-3-5, .row.row--middle-align .palm-4-5, .row.row--middle-align .palm-5-5, .row.row--middle-align .header__left-side, .row.row--middle-align .nav__container {
    vertical-align: middle; }

.desk-1-12, .desk-2-12, .desk-3-12, .desk-4-12, .desk-5-12, .desk-6-12, .desk-7-12, .desk-8-12, .desk-9-12, .desk-10-12, .desk-11-12, .desk-12-12, .desk-1-5, .desk-2-5, .desk-3-5, .desk-4-5, .desk-5-5, .lap-1-12, .lap-2-12, .lap-3-12, .lap-4-12, .lap-5-12, .lap-6-12, .lap-7-12, .lap-8-12, .lap-9-12, .lap-10-12, .lap-11-12, .lap-12-12, .lap-1-5, .lap-2-5, .lap-3-5, .lap-4-5, .lap-5-5, .palm-1-12, .palm-2-12, .palm-3-12, .palm-4-12, .palm-5-12, .palm-6-12, .palm-7-12, .palm-8-12, .palm-9-12, .palm-10-12, .palm-11-12, .palm-12-12, .palm-1-5, .palm-2-5, .palm-3-5, .palm-4-5, .palm-5-5, .header__left-side, .nav__container {
  text-align: left;
  direction: ltr;
  vertical-align: top;
  display: inline-block;
  box-sizing: border-box;
  margin-right: -.244em;
  white-space: normal;
  width: 100%;
  padding-left: 64px; }

.row.row--flush > .desk-1-12, .row.row--flush > .desk-2-12, .row.row--flush > .desk-3-12, .row.row--flush > .desk-4-12, .row.row--flush > .desk-5-12, .row.row--flush > .desk-6-12, .row.row--flush > .desk-7-12, .row.row--flush > .desk-8-12, .row.row--flush > .desk-9-12, .row.row--flush > .desk-10-12, .row.row--flush > .desk-11-12, .row.row--flush > .desk-12-12, .row.row--flush > .desk-1-5, .row.row--flush > .desk-2-5, .row.row--flush > .desk-3-5, .row.row--flush > .desk-4-5, .row.row--flush > .desk-5-5, .row.row--flush > .lap-1-12, .row.row--flush > .lap-2-12, .row.row--flush > .lap-3-12, .row.row--flush > .lap-4-12, .row.row--flush > .lap-5-12, .row.row--flush > .lap-6-12, .row.row--flush > .lap-7-12, .row.row--flush > .lap-8-12, .row.row--flush > .lap-9-12, .row.row--flush > .lap-10-12, .row.row--flush > .lap-11-12, .row.row--flush > .lap-12-12, .row.row--flush > .lap-1-5, .row.row--flush > .lap-2-5, .row.row--flush > .lap-3-5, .row.row--flush > .lap-4-5, .row.row--flush > .lap-5-5, .row.row--flush > .palm-1-12, .row.row--flush > .palm-2-12, .row.row--flush > .palm-3-12, .row.row--flush > .palm-4-12, .row.row--flush > .palm-5-12, .row.row--flush > .palm-6-12, .row.row--flush > .palm-7-12, .row.row--flush > .palm-8-12, .row.row--flush > .palm-9-12, .row.row--flush > .palm-10-12, .row.row--flush > .palm-11-12, .row.row--flush > .palm-12-12, .row.row--flush > .palm-1-5, .row.row--flush > .palm-2-5, .row.row--flush > .palm-3-5, .row.row--flush > .palm-4-5, .row.row--flush > .palm-5-5, .row.row--flush > .header__left-side, .row.row--flush > .nav__container {
  padding-left: 0; }
```

The compiled CSS after removing the `@extend %column` from the grid widths and using attribute selectors

```css
.row {
  margin-left: -64px; }
  .row.row--reverse {
    direction: rtl;
    text-align: left; }
  .row.row--centred {
    text-align: center; }
  .row.row--flush {
    margin-left: 0; }
  .row.row--small {
    margin-left: -32px; }
    .row.row--small [class*='desk-'], .row.row--small [class*='lap-'], .row.row--small [class*='palm-'], .row.row--small .header__left-side, .row.row--small .nav__container {
      padding-left: 32px; }
  .row.row--tiny {
    margin-left: -16px; }
    .row.row--tiny [class*='desk-'], .row.row--tiny [class*='lap-'], .row.row--tiny [class*='palm-'], .row.row--tiny .header__left-side, .row.row--tiny .nav__container {
      padding-left: 16px; }
  @media only screen and (max-width: 34.375em) {
    .row.row--tiny--on-mobile {
      margin-left: -16px; }
      .row.row--tiny--on-mobile [class*='desk-'], .row.row--tiny--on-mobile [class*='lap-'], .row.row--tiny--on-mobile [class*='palm-'], .row.row--tiny--on-mobile .header__left-side, .row.row--tiny--on-mobile .nav__container {
        padding-left: 16px; } }
  .row.row--middle-align [class*='desk-'], .row.row--middle-align [class*='lap-'], .row.row--middle-align [class*='palm-'], .row.row--middle-align .header__left-side, .row.row--middle-align .nav__container {
    vertical-align: middle; }

[class*='desk-'], [class*='lap-'], [class*='palm-'], .header__left-side, .nav__container {
  text-align: left;
  direction: ltr;
  vertical-align: top;
  display: inline-block;
  box-sizing: border-box;
  margin-right: -.244em;
  white-space: normal;
  width: 100%;
  padding-left: 64px; }

.row.row--flush > [class*='desk-'], .row.row--flush > [class*='lap-'], .row.row--flush > [class*='palm-'], .row.row--flush > .header__left-side, .row.row--flush > .nav__container {
  padding-left: 0; }
```

I'm hoping that this will limit the amount of extra selectors when extending responsive row classes to other selectors.

Can anyone see any problems with this change? I would prefer to do away with the need for these selectors all together by creating a class of `column` that would be attached to every grid element. Can you remind me why this wasn't the case? I find that I'm having to write `palm-12-12` (or `c-12-12`) on almost every grid element anyway; whereas you could make the `column` class 100% by default on mobile?
