### ISSUE TITLE
Add fourth breakpoint by default

### ISSUE THREAD

**Issue by lukepearce** [ten4design/ten4-framework#61]
Our responsive game is weak at the moment. An iPad in landscape can't look good with our default desktop layout.. Lets add a fourth breakpoint for smaller laptop screens.

I'm going to implement on flowers so

```
palm: <500px
hand: >500px <900px
lap:  >900px <1200px
desk: >1200px
```

**Comment by charliegrinsted** [comment]
Surprised to hear this coming from Luke "Agnostic" Pearce ;)

Surely we should be getting into the habit of simply adding breakpoints when the design falls down, rather than for devices...

**Comment by lukepearce** [comment]
These are our fixed breakpoints for simple and quick responsive layouts.

Ideally we'd never use these are all layouts would be completely bespoke depending on their content... but thats never going to happen.

**Comment by andygrn** [comment]
Yeah I didn't intend those breakpoints to be actually used, they are just examples. Should probably remove them.

**Comment by lukepearce** [comment]
They're used to generate the grid though right?

**Comment by andygrn** [comment]
Yes, but every design is different, they should be adjusted.

**Comment by lukepearce** [comment]
aye, but by default people will stick with three.. I think we should introduce a fourth as standard

**Comment by andygrn** [comment]
Each breakpoint in that list adds a shit ton of grid CSS, I'd rather it was empty by default and we add them as we need them.

**Comment by charliegrinsted** [comment]
*grabs popcorn*

**Comment by lukepearce** [comment]
I think we should have a maximum of 4 default breakpoints for rapid development.

If we need more bespoke layout tweaks we should move to an `@extend` method to cut down on shit tons of redundant grid CSS

**Comment by andygrn** [comment]
It takes 2 seconds to add a breakpoint! Keep in mind this list is only for *grid* breakpoints - if you need a breakpoint for e.g. switch-to-mobile-nav-width, that should be some other variable somewhere. Zab's got 4 grid breakpoints and a bunch of other non-grid ones too.

How would an `@extend` method work?

**Comment by lukepearce** [comment]
UPDATE: turns out I forgot that you can't `@extend` inside `@includes` but because the rules we want to "extend" are super simple we'd just add variables for our width values.

---

Its grid layout but its also "one/two/three/four sizes fits all" mindset. The `@extend` method would work like so:

How it is currently (ignore syntax errors!)

```html
<row>
  <desk-6-12>
  <desk-6-12>
</row>
```

```scss
.desk-6-12 {
  width: 50%;
}
```

`@extend` method

```html
<row>
  <article__image>
  <article__body>
</row>
```

```scss
.article__image {
  @include media( lap ) {
     width: $6-12
  }
  @include media( hand ) {
     width: $4-12;
  }
```

This means we don't have shit tons of grid CSS and unlimited possibilities for very bespoke responsive layouts. You could prefix the classes like so `g--article__image` to differentiate between the layout and the style - for instance we don't ever attached any extra rules to divs with `desk-6-12` on etc.

**Comment by andygrn** [comment]
How do grid gutters, centering, reversal etc. work with this approach?

**Comment by lukepearce** [comment]
Have a base column class or a matching selector like so

```html
<row>
  <column article__image>
</row>
```

```scss
.column {
 gutter: rules
}

.row--centered {
  .column {
    center: rules;
  }
}
```

or 

```html
<row>
   <g--article__image>
</row>
```

```scss
[class*=g--] {
  gutter: rules;
}

.row--centered {
  [class*=g--]{
    center: rules;
  }
}
```
